### ISSUE TITLE
Consider allowing ids to be integers or strings

### ISSUE THREAD

**Issue by killerbgt** [540co/eads#78]
Allow ids to be either strings or integers

**Comment by jbjonesjr** [comment]
From a schema validation standpoint, strings in my experience provide the forward-compatible functionality when you outgrow integers.

I used to manage an API where we eventually moved from integer-based ids to GUIDS, and the backed in schema acceptance (instead of just client checking) made that a pain.

My 2 cents. In general, I'm a :+1: to the schema/high level details being pretty open, and then let individual implementations or versions add additional restrictions/validations.

**Comment by treyau21** [comment]
I agree that this may be an area where we could be less prescriptive
